create table if not exists public.member_emails (
  email text primary key,
  role text not null default 'member' check (role in ('owner', 'member')),
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  channel text not null check (channel in ('general', 'constitution', 'hustlers', 'tax-reaper', 'loans', 'suits-tism')),
  body text not null check (char_length(body) <= 1000),
  author_id uuid not null references auth.users(id) on delete cascade,
  author_email text not null,
  created_at timestamptz not null default now()
);

alter table public.member_emails enable row level security;
alter table public.messages enable row level security;

create policy "Members can read their own allowlist record"
on public.member_emails
for select
to authenticated
using (lower(email) = lower(auth.jwt() ->> 'email'));

create policy "Signed-in members can read messages"
on public.messages
for select
to authenticated
using (
  exists (
    select 1
    from public.member_emails members
    where lower(members.email) = lower(auth.jwt() ->> 'email')
  )
);

create policy "Signed-in members can create messages"
on public.messages
for insert
to authenticated
with check (
  auth.uid() = author_id
  and exists (
    select 1
    from public.member_emails members
    where lower(members.email) = lower(auth.jwt() ->> 'email')
  )
);

alter publication supabase_realtime add table public.messages;

-- Add your allowed users here before inviting them.
-- insert into public.member_emails (email, role)
-- values ('you@example.com', 'owner')
-- on conflict (email) do update set role = excluded.role;
